Re-Spring/Do-Rering_JAVA

- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
- src/main/java/respring/dorering/rest/story/entity/Story.java
- src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 메인 홈 동화 리스트를 구현하기 위한 코드
* * *
- 조금 더 수정 할 수 있음
* * *
- StoryController의 URL 경로가 프론트의 Main.js 의 fetch URL과 일치해야 함
* * *
- 아직 리스트가 나오지 않음
* * *
-
> [Feature]메인 홈 동화 리스트 구현 중

- src/main/java/respring/dorering/rest/auth/config/JwtSecurityConfig.java
- src/main/java/respring/dorering/rest/auth/config/SecurityConfig.java
- src/main/java/respring/dorering/rest/auth/controller/UserController.java
- src/main/java/respring/dorering/rest/auth/jwt/CustomUserDetails.java
- src/main/java/respring/dorering/rest/auth/jwt/JWTFilter.java
- src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
- src/main/java/respring/dorering/rest/auth/service/UserService.java
* * *
- 
* * *
* * *
- unauthocication 오류에서 무한루프 오류로 변경되었습니다.. 무한루프 오류 수정중
- 설명을 작성하세요.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
- 테스트 내용 및 결과를 작성하세요.
- 테스트 내용 및 결과를 작성하세요.
* * *
- 요청 사항을 작성하세요.
- 요청 사항을 작성하세요.
> [Bug]로그인 오류 수정중

- build.gradle
- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/entity/Story.java
- src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 메인 홈 동화 리스트 구현 완료
* * *
- 
* * *
- Controller에 @CrossOrigin(origins = "http://localhost:3000") 를 적어 프론트 포트번호를 적어서 연결을 시켜줌
- @RequestMapping("/stories") 의 URL을 프론트쪽 js에 fetch로 연결해줌
* * *
- 
* * *
-
> [Feature] 메인 홈 동화 리스트 구현 완료

- src/main/java/respring/dorering/rest/auth/config/SecurityConfig.java
- src/main/java/respring/dorering/rest/auth/controller/UserController.java
- src/main/java/respring/dorering/rest/auth/jwt/CustomUserDetails.java
- src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
- src/main/java/respring/dorering/rest/auth/service/CustomUserDetailsService.java
- src/main/java/respring/dorering/rest/auth/service/UserService.java
* * *
* * *
* * *
- 로그인 에러 수정
* * *
- 토큰 인증 오류(인증되지 않은 사용자) 에러 -> authenticationManager 관련 무한루프 에러 -> 해결
* * *
- 
* * *
- 
* * *
> [BugFix] 로그인 에러 수정, 구현

- src/main/java/respring/dorering/rest/search/controller/SearchController.java
- src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
- src/main/java/respring/dorering/rest/search/entity/FairyTale.java
- src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
- src/main/java/respring/dorering/rest/search/service/SearchService.java
* * *
* * *
- 검색 기능을 위한 기본 베이스 구성
* * *
컨트롤러, entity, service,repository, dto 생성
> [Feature] 검색 기능을 위한 기본 베이스 구현

- src/main/java/respring/dorering/rest/auth/dto/TokenDTO.java
- src/main/java/respring/dorering/rest/auth/jwt/CustomUserDetails.java
- src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
- src/main/java/respring/dorering/rest/auth/service/CustomUserDetailsService.java
* * *
- 
* * *
* * *
- 로그인 유저 토큰 정보에 가입일과 전화번호를 추가했습니다.
* * *
* * *
* * *
- ![image](https://github.com/Re-Spring/Do-Rering_JAVA/assets/140992400/c6929eed-0226-4963-845e-760326a7fb09)
* * *
> [Refactoring] 토큰 정보 추가

- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 동화 상세 페이지 구현 중
* * *
- 
* * *
- 상세 페이지의 테이블을 잘못 사용하여서 다시 구현 해야 함
* * *
- 
* * *
-
> [Feature] 동화 상세 페이지 구현 중

- src/main/java/respring/dorering/rest/search/controller/SearchController.java
- src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
- src/main/java/respring/dorering/rest/search/entity/FairyTale.java
- src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
- src/main/java/respring/dorering/rest/search/service/SearchService.java
* * *
통합검색 기능 활성화
실행했을 때 오류 사항 수정
> [Feature] search 수정본

- src/main/java/respring/dorering/rest/fairytale/controller/DetailController.java
- src/main/java/respring/dorering/rest/fairytale/dto/DetailDTO.java
- src/main/java/respring/dorering/rest/fairytale/entity/Detail.java
- src/main/java/respring/dorering/rest/fairytale/repository/DetailRepository.java
- src/main/java/respring/dorering/rest/fairytale/service/DetailService.java
- src/main/resources/application.yml
* * *
- 
* * *
* * *
- 동화 상세페이지 구현 중
* * *
- 코드 구현 전입니다.
* * *
- 
* * *
- 
* * *
-
> [Feature] 상세 페이지 구현 중

- src/main/java/respring/dorering/rest/auth/controller/UserController.java
- src/main/java/respring/dorering/rest/auth/entity/User.java
- src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
- src/main/java/respring/dorering/rest/auth/service/UserService.java
* * *
- 
* * *
* * *
- 아이디 찾기
- 비밀번호 찾기
* * *
* * *
* * *
* * *
> [Feature] 아이디 비밀번호 찾기 구현

- src/main/java/respring/dorering/rest/auth/service/UserService.java
- src/main/resources/application.yml
* * *
- 
* * *
* * *
- 내 정보 수정 기능 완료
* * *
- 
* * *
"""
public class UpdateUserDTO {
private String phone;
private String userName;
private String userId;
// Getters and Setters
public  String getUserId(){
return userId;
}
public String getUserName() {
return userName;
}
public void setUserName(String userName) {
this.userName = userName;
}
public String getPhone() {
return phone;
}
public void setPhone(String phone) {
this.phone = phone;
}
"""
dto만 updateDTO를 따로 만들고 다른 코드는 기존 user 코드에 추가했습니다.
* * *
- 기능 수정이 아주 잘 되고 있음
* * *
-
> [Feature] 내 정보 수정 기능 완료

- src/main/java/respring/dorering/rest/fairytale/controller/DetailController.java
- src/main/java/respring/dorering/rest/fairytale/dto/DetailDTO.java
- src/main/java/respring/dorering/rest/fairytale/entity/Detail.java
- src/main/java/respring/dorering/rest/fairytale/repository/DetailRepository.java
- src/main/java/respring/dorering/rest/fairytale/service/DetailService.java
- src/main/java/respring/dorering/rest/search/controller/SearchController.java
- src/main/java/respring/dorering/rest/search/dto/SearchDTO.java
- src/main/java/respring/dorering/rest/search/entity/FairyTale.java
- src/main/java/respring/dorering/rest/search/repository/SearchRepository.java
- src/main/java/respring/dorering/rest/search/service/SearchService.java
검색 기능 수정
* * *
* * *
fairycode 추가
fairycode 카테고리 추가
* * *
> Feature 검색

- sql/script.sql
- src/main/resources/application.yml
* * *
* * *
- SQL 스크립트, yml 파일 수정
* * *
```
USE dorering;
CREATE TABLE `user_info` (
`user_code` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(10),
`id` VARCHAR(20),
`pwd` VARCHAR(20),
`phone` VARCHAR(20),
`role` VARCHAR(20),
`withdrawal_status` VARCHAR(20),
`voice_id` VARCHAR(20),
`withdrawal_date` DATE,
`enroll_date` DATE
);
CREATE TABLE `fairytale_info` (
`fairytale_code` INTEGER NOT NULL PRIMARY KEY,
`user_code` INTEGER NOT NULL,
`fairytale_summary` VARCHAR(5000),
`fairytale_title` VARCHAR(255),
`fairytale_genre` VARCHAR(255),
`fairytale_thumb` VARCHAR(255),
`fairytale_image` VARCHAR(255),
FOREIGN KEY (`user_code`) REFERENCES `user_info` (`user_code`)
);
CREATE TABLE `voice` (
`voice_code` INTEGER NOT NULL PRIMARY KEY,
`fairytale_code` INTEGER NOT NULL,
`user_code` …
```
> [Refactoring] yml 파일 수정, sql스크립트 수정

- sql/script.sql
* * *
* * *
- SQL 스크립트 수정 하였습니다.
* * *
```
USE dorering;
CREATE TABLE `user_info` (
`user_code` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(10),
`id` VARCHAR(20),
`pwd` VARCHAR(255),
`phone` VARCHAR(20),
`role` VARCHAR(20),
`withdrawal_status` VARCHAR(20),
`voice_id` VARCHAR(20),
`withdrawal_date` DATE,
`enroll_date` DATE
);
CREATE TABLE `fairytale_info` (
`fairytale_code` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`user_code` INTEGER NOT NULL,
`fairytale_summary` VARCHAR(5000),
`fairytale_title` VARCHAR(255),
`fairytale_genre` VARCHAR(255),
`fairytale_thumb` VARCHAR(255),
`fairytale_image` VARCHAR(255),
FOREIGN KEY (`user_code`) REFERENCES `user_info` (`user_code`)
);
CREATE TABLE `voice` (
`voice_code` INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
`fairytale_code` …
```
> [Refactorying] SQL스크립트 수정하였습니다

- src/main/java/respring/dorering/rest/auth/controller/UserController.java
- src/main/java/respring/dorering/rest/auth/entity/User.java
- src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
- src/main/java/respring/dorering/rest/auth/service/UserService.java
- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
- src/main/java/respring/dorering/rest/story/dto/StoryDetailDTO.java
- src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 내 동화 보기 구현 및 회원 탈퇴 구현 중
* * *
-
* * *
- mysql의 event_scheduler를 사용해서 탈퇴 후 30일 동안 재가입 불가하도록 설정해줌
"""
CREATE EVENT IF NOT EXISTS update_rejoin_status
ON SCHEDULE EVERY 1 DAY
STARTS TIMESTAMP(CURRENT_DATE, '00:00:00')
DO
UPDATE user_info
SET withdrawal_status = 'N'
WHERE withdrawal_status = 'Y' AND withdrawal_date <= NOW() - INTERVAL 1 MONTH;
"""
* * *
- 탈퇴 여부는 바뀌는데 데이터가 삭제가 되지 않아서 조금 더 봐야 할 것 같음
* * *
-
> [Feature] 회원탈퇴 및 내 동화 보기 구현

- src/main/java/respring/dorering/rest/auth/controller/UserController.java
- src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
* * *
- 로그인 토큰 만료
* * *
* * *
- 로그인 만료에 있어서 두 가지 방향으로 작업중입니다.
- 1. 일정 시간 동작(마우스, 키보드) 감지 되지 않으면 로그아웃
- 2. 토큰 만료 시간이 지나면 로그아웃
- 현재 1번은 프론트 작업만으로 완료되었고 2번이 제대로 동작하지 않아 수정중입니다.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 토큰 만료 시간 설정
```
public class TokenProvider {
private static final long ACCESS_TOKEN_EXPIRE_TIME = 1000 * 60 * 30;
public TokenDTO generateTokenDTO(Authentication authentication){
long now = (new Date()).getTime();
Date tokenExpiresIn = new Date(now + ACCESS_TOKEN_EXPIRE_TIME);
log.info("tokenExpiresIn 확인 : {}", tokenExpiresIn);
String accessToken = Jwts.builder()
.setSubject(authentication.getName())
.claim("userCode", userCode)
.claim("userId", userId)
.claim("userVoiceId", userVoiceId)
.claim("userName", userName)
.claim("userRole", userRole)
.claim("phone", phone) …
```
> [Feature] 로그인 만료-1

- src/main/java/respring/dorering/rest/auth/entity/User.java
- src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
- src/main/java/respring/dorering/rest/auth/service/UserService.java
* * *
- 
* * *
* * *
- 탈퇴 기능 수정
* * *
- 탈퇴 후 한 달이 지나면 다시 휴면 계정이 풀리는 것이 아닌 데이터가 삭제 되어 재가입 되도록 수정함
* * *
- 
* * *
- 
* * *
-
> [Feature] 회원 탈퇴 수정 완료

- src/main/java/respring/dorering/rest/auth/jwt/TokenProvider.java
- src/main/java/respring/dorering/rest/auth/repository/UserRepository.java
* * *
- 
* * *
* * *
- 토큰 만료에 의산 로그아웃 구현
- 토큰 만료 시간을 6시간으로 변경했습니다.
* * *
* * *
- 토큰 만료 시간 설정(TokenProvider.java)
```
private static final long ACCESS_TOKEN_EXPIRE_TIME = 1000 * 60 * 60 * 6;
```
* * *
* * *
> [Refactoring] 로그인 만료-2

- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 내 동화 페이지 구현 중
* * *
- 
* * *
-아직 구현 중입니다.
* * *
- 
* * *
-
> [Feature] 내 동화 페이지 구현 중

- build.gradle
- src/main/java/respring/dorering/rest/CustomerService/controller/CustomerServicePostController.java
- src/main/java/respring/dorering/rest/CustomerService/dto/CustomerServicePostDto.java
- src/main/java/respring/dorering/rest/CustomerService/entity/CustomerServicePost.java
- src/main/java/respring/dorering/rest/CustomerService/repository/CustomerServicePostRepository.java
- src/main/java/respring/dorering/rest/CustomerService/service/CustomerServicePostService.java
> [Feature 고객센터 백엔드]

- Dockerfile
* * *
* * *
- 배포를 위한 도커 파일 생성
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
- 테스트 내용 및 결과를 작성하세요.
- 테스트 내용 및 결과를 작성하세요.
* * *
- 요청 사항을 작성하세요.
- 요청 사항을 작성하세요.
> [Feature] dockerfile add

- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/entity/Story.java
- src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 내 동화 페이지 구현 완료
* * *
- 
* * *
- 
* * *
- 
* * *
-
> [Feature] 내 동화 페이지 구현 완료

- src/main/java/respring/dorering/rest/admin/config/ApiKeyConfiguration.java
- src/main/java/respring/dorering/rest/admin/controller/AdminController.java
- src/main/java/respring/dorering/rest/admin/service/AdminService.java
* * *
- 
* * *
* * *
- 탈퇴 회우너 데이터 관리 기능 계쏙 수정중
* * *
* * *
- 현재 코드 기반으로 실행 시 해당하는 보이스 아이디를 elevenlabs에서 찾을 수 없다는 에러 발생. 존재하는 아이디인데도 발생. 그래서 일단 파이썬 백에서 다시 작성해볼 예정입니다.
* * *
* * *
> [Feature] 탈퇴 회원 기간 만료 후 정보 삭제 - 2

- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/entity/Story.java
- src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 메인 동화 리스트 나눴습니다.
* * *
- 
* * *
- 동화 리스트 띄우는 것을 userStories와 adminStories 둘로 나눈 뒤 카테고리는 userStories에서만 작동 되도록 했습니다.
* * *
- 
* * *
-
> [Feature] 메인 동화 리스트 나누기

- src/main/java/respring/dorering/rest/story/controller/StoryController.java
- src/main/java/respring/dorering/rest/story/dto/StoryDTO.java
- src/main/java/respring/dorering/rest/story/dto/StoryDetailDTO.java
- src/main/java/respring/dorering/rest/story/entity/FairytaleVideoInfo.java
- src/main/java/respring/dorering/rest/story/entity/Story.java
- src/main/java/respring/dorering/rest/story/repository/StoryRepository.java
- src/main/java/respring/dorering/rest/story/repository/VideoRepository.java
- src/main/java/respring/dorering/rest/story/service/StoryService.java
* * *
- 
* * *
* * *
- 동화 상세페이지 동화 추가
* * *
- 
* * *
- 
* * *
- 
* * *
-
> [Feature] 상세페이지 동화 추가
